        SUBROUTINE GETPARTINFOC(NAME, LOCNUM, JTYPE, USER_NUMBER, JRCD)
        EXTERNAL GETPARTINFO
        INTEGER LOCNUM, JTYPE, USER_NUMBER, JRCD
        CHARACTER NAME_*80
        CALL GETPARTINFO(LOCNUM, JTYPE, NAME_, USER_NUMBER, JRCD)
        NAME = NAME_
        END

        SUBROUTINE GETELEMNUMBERUSER(LOCNUM, USER_NUMBER)
        EXTERNAL GETPARTINFO
        CHARACTER NAME*80
        CALL GETPARTINFO(LOCNUM, 1, NAME, USER_NUMBER, JRCD)
        END

        SUBROUTINE GETPARTNAME(NAME)
        EXTERNAL GETPARTINFO
        CHARACTER NAME*80
        CALL GETPARTINFO(LOCNUM, 1, NAME, USER_NUMBER, JRCD)
        END